[graph]
all-features = true

[advisories]
yanked = "warn"

[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "either"
copyleft = "allow"

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
