[package]
name = "synapse-sync"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
synapse-core = { path = "../synapse-core" }
synapse-local-store = { path = "../synapse-local-store" }
synapse-protocol = { path = "../synapse-protocol" }
uuid = "1.18.1"

[lints]
workspace = true
